name: Laravel

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Check coding convention by PHP_CodeSniffer
      run: ./vendor/bin/phpcs
    - name: PHP mess detector
      run:  ./vendor/bin/phpmd app,database,routes,tests text phpmd.xml
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
  
  # Auto deploy to stg 
  deploy-staging-hapo:
    name: Deploy to example.com
    runs-on: ubuntu-latest
    needs: laravel-tests
    if: ${{ github.ref == 'refs/heads/develop' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy
        uses: musps/action-deployer-php@master
        with:
          args: deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
              